---
metadata:
  name: Gbook
  short_name: Gbook
  description: Gbook - awesome GitBook-like documentation for Risk and Acturary
  language: en
  pathPrefix: "/ifrs"
  siteImage:
  favicon: "/assets/GofFavicon32.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/GoFwobg96.png"
  logolink: "/"
  helpUrl: ""
  links:
    - text: Gbook
      link:  https://gof77.github.io/gbook
      external: false
    - text: IFRS
      link: https://gof77.github.io/ifrs
      external: true
    - text: References
      link: "/"
      external: false
      submenus:
        - text: KICS
          link: "/"
        - text: IFRS17
          link: https://gof77.github.io/ifrs
        - text: GESG
          link: https://gof77.github.io/gesg
    - text: Solutions
      link: "/"
      external: false
      submenus:
        - text: GMV
          link: https://gof77.github.io/ifrs
        - text: GESG
          link: https://gof77.github.io/gesg
sidebar:
  enabled: true
  #forcedNavOrder:
  #    - "/kics"
  #    - "/configuration/basic"
  #   - "/configuration/advanced"
  #expanded:
  #  - "/configuration/setting-up"
  groups:
    - order: 1
      path: "/2."
      title: ":rocket: 2.계약관리"
    - order: 2
      path: "/3."
      title: ":wrench: 3.최초인식 및 측정"
    - order: 3
      path: "/4."
      title: ":writing_hand: 4.후속측정"
    - order: 4
      path: "/5."
      title: ":rocket: 5.보험료 배분 접근법"
    - order: 5
      path: "/6."
      title: ":computer: 6.변동수수료 접근법"
    - order: 6
      path: "/7."
      title: ":computer: 7.출재보험계약"
    - order: 7
      path: "/8."
      title: ":computer: 8.표시 및 공"
  links:
    - text: GoF
      link: https://github.com/filipowm/boogi
    - text: React
      link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    trademark:
    name: 
    link: 
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/GofFavicon32.png"

social:
  github: 
  linkedin: 
  twitter: 

features:
  darkMode:
    enabled: true  
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi 
    type: github
    editable: false
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: false
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: false
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
